# Generated by Django 5.1.6 on 2025-03-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('app', 'app'), ('article', 'article'), ('video', 'video')], default='app', max_length=20),
        ),
    ]
