# Generated by Django 5.1.6 on 2025-04-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='repo_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
