# Generated by Django 5.1.6 on 2025-04-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_blog_repo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='repo_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
