# Generated by Django 5.1.6 on 2025-05-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_blog_description_alter_blog_repo_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='link',
            new_name='site_link',
        ),
        migrations.AddField(
            model_name='blog',
            name='screenshot_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
