# Generated by Django 5.1.6 on 2025-05-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_link_blog_site_link_blog_screenshot_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='site_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
