# Generated by Django 5.1.6 on 2025-05-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_blog_site_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('app', 'app'), ('tutorial', 'tutorial')], default='app', max_length=20),
        ),
    ]
